const API_ORIGIN="https://htn-api-production-ab6d.up.railway.app";const API_BASE=API_ORIGIN+"/api/discovery";const ORGANIZATION_ID="0e6f5b36-98aa-4d84-a142-b48c6dd3eb1f";
const $=s=>document.querySelector(s),headers=()=>({Accept:"application/json","x-organization-id":ORGANIZATION_ID});let searches=[],profiles=[];
async function request(path,o={}){const r=await fetch(API_BASE+path,{...o,headers:{...headers(),...(o.headers||{})}}),p=await r.json().catch(()=>({}));if(!r.ok||!p.success)throw Error(p.message||"Request failed");return p.data}
function toast(m){$("#toast").textContent=m;$("#toast").classList.add("show");setTimeout(()=>$("#toast").classList.remove("show"),2600)}
function date(v){return v?new Intl.DateTimeFormat(undefined,{dateStyle:"medium",timeStyle:"short"}).format(new Date(v)):"—"}
async function loadSearches(){const data=await request("/searches?limit=100");searches=data.items||[];const f=$("#search-filter");f.replaceChildren(new Option("All searches",""));searches.forEach(s=>f.add(new Option(s.name,s.id)));renderSearches();$("#metric-searches").textContent=searches.length;$("#metric-active").textContent=searches.filter(s=>s.status==="ACTIVE").length;await loadProfiles()}
function renderSearches(){const root=$("#search-list");if(!searches.length){root.innerHTML='<div class="empty">No discovery searches yet.</div>';return}root.replaceChildren(...searches.map(s=>{const e=document.createElement("article");e.className="search-item";const b=document.createElement("div");b.innerHTML=`<div class="search-name"></div><div class="query"></div><div class="meta-row"><span class="pill ${s.status.toLowerCase()}">${s.status}</span><span>Created ${date(s.createdAt)}</span></div>`;b.querySelector(".search-name").textContent=s.name;b.querySelector(".query").textContent=s.query;const a=document.createElement("div"),btn=document.createElement("button");btn.className="button secondary";btn.textContent=s.status==="ACTIVE"?"Run search":"Activate";btn.onclick=()=>s.status==="ACTIVE"?executeSearch(s.id):activateSearch(s.id);a.append(btn);e.append(b,a);return e}))}
async function activateSearch(id){try{await request("/searches/"+id,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({status:"ACTIVE"})});toast("Search activated");await loadSearches()}catch(e){toast(e.message)}}
async function executeSearch(id){try{toast("Running search…");await request("/searches/"+id+"/execute",{method:"POST"});toast("Search completed");await loadSearches()}catch(e){toast(e.message)}}
async function loadProfiles(){profiles=[];for(const s of searches){try{const runs=await request("/searches/"+s.id+"/runs"),run=runs[0];if(!run)continue;const ps=await request("/runs/"+run.id+"/profiles");profiles.push(...ps.map(p=>({...p,searchId:s.id,searchName:s.name})))}catch(e){console.error(e)}}$("#metric-profiles").textContent=profiles.length;const latest=[...profiles].sort((a,b)=>new Date(b.discoveredAt)-new Date(a.discoveredAt))[0];$("#metric-latest").textContent=latest?date(latest.discoveredAt):"—";renderProfiles()}
function renderProfiles(){const id=$("#search-filter").value,items=profiles.filter(p=>!id||p.searchId===id).sort((a,b)=>new Date(b.discoveredAt)-new Date(a.discoveredAt)),root=$("#profile-list");if(!items.length){root.innerHTML='<div class="empty">No discovered profiles to show.</div>';return}root.replaceChildren(...items.map(p=>{const e=document.createElement("article");e.className="profile-card";const b=document.createElement("div");b.innerHTML='<div class="profile-name"></div><div class="profile-headline"></div><div class="profile-snippet"></div><div class="meta-row"></div>';b.querySelector(".profile-name").textContent=p.name||p.headline||"Discovered profile";b.querySelector(".profile-headline").textContent=p.headline||"Public profile";b.querySelector(".profile-snippet").textContent=p.snippet||"No snippet available.";b.querySelector(".meta-row").innerHTML=`<span class="pill">${p.status}</span><span>${p.searchName}</span>`;const a=document.createElement("div");a.className="profile-actions";const l=document.createElement("a");l.href=p.profileUrl;l.target="_blank";l.rel="noopener noreferrer";l.textContent="View profile ↗";a.append(l);e.append(b,a);return e}))}
$("#search-form").addEventListener("submit",async e=>{e.preventDefault();const fd=new FormData(e.target),csv=n=>String(fd.get(n)||"").split(",").map(x=>x.trim()).filter(Boolean);try{await request("/searches",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name:String(fd.get("name")||"").trim(),roles:csv("roles"),skills:csv("skills"),locations:csv("locations"),companies:csv("companies"),sources:csv("sources")})});$("#search-dialog").close();e.target.reset();toast("Search created");await loadSearches()}catch(x){toast(x.message)}});
$("#new-search-btn").onclick=()=>$("#search-dialog").showModal();$("#close-dialog").onclick=$("#cancel-dialog").onclick=()=>$("#search-dialog").close();$("#refresh-searches").onclick=()=>loadSearches().catch(e=>toast(e.message));$("#refresh-profiles").onclick=()=>loadProfiles().catch(e=>toast(e.message));$("#search-filter").onchange=renderProfiles;loadSearches().catch(e=>{console.error(e);toast(e.message)});